version: 2.1

commands:
  yarn_install:
    description: Yarn install and link deps
    steps:
      - run:
          name: Yarn Install
          command: yarn install --immutable

  checkout_monorepo:
    description: Checkout the git mono repo with a standard root
    steps:
      - checkout:
          path: /home/circleci/spookysofware.dev

executors:
  default_www_node_env:
    docker:
      - image: circleci/node:16.13.0
    working_directory: /home/circleci/spookysofware.dev/www

jobs:
  fmt_www:
    executor: default_www_node_env
    steps:
      - checkout_monorepo
      - run:
          name: Checking Formatting
          command: yarn run prettier . --check

  typecheck_www:
    executor: default_www_node_env
    steps:
      - checkout_monorepo
      - yarn_install
      - run:
          name: Creating scss module defintions
          command: yarn run tsm src
      - run:
          name: Type checking
          command: yarn run tsc

  build_www_static_html:
    executor: default_www_node_env
    steps:
      - checkout_monorepo
      - yarn_install
      - run:
          name: Building
          command: yarn run clean && yarn run build
          environment:
            GATSBY_CPU_COUNT: "2"
      - persist_to_workspace:
          root: "../"
          paths:
            - www/public

  deploy_infrastructure:
    docker:
      - image: dairyisscary/terraform:0.13.5
    working_directory: /home/circleci/spookysofware.dev/infra
    steps:
      - checkout_monorepo
      - run:
          name: Initing Terraform
          command: terraform init
      - run:
          name: Forming Infrastructure
          command: |
            mkdir -p output
            terraform apply -auto-approve
            terraform output -json > output/terraform.json
      - persist_to_workspace:
          root: "../"
          paths:
            - infra/output

  deploy_www_upload:
    docker:
      - image: dairyisscary/awscli:1.14.36
    steps:
      - checkout_monorepo
      - attach_workspace:
          at: /home/circleci/spookysofware.dev
      - run:
          name: Uploading to S3 Bucket
          command: |
            cd /home/circleci/spookysofware.dev/www
            BUCKET_NAME=$(cat ../infra/output/terraform.json | jq '.www_static_bucket_name.value' -r) bash bin/upload-to-s3.sh
      - run:
          name: Invalidating Cloudfront
          command: |
            cd /home/circleci/spookysofware.dev
            aws cloudfront create-invalidation \
              --distribution-id $(\
                 cat infra/output/terraform.json | \
                 jq '.www_cdn_id.value' -r \
              ) \
              --paths '/*'

workflows:
  version: 2
  "Check and Deploy":
    jobs:
      - deploy_infrastructure:
          filters:
            branches:
              only: production
      - fmt_www
      - typecheck_www
      - build_www_static_html:
          requires:
            - typecheck_www
            - fmt_www
      - deploy_www_upload:
          requires:
            - deploy_infrastructure
            - build_www_static_html
          filters:
            branches:
              only: production
